---

AWSTemplateFormatVersion: '2010-09-09'


Description: ECR Repo


Outputs:
  EcrRepo:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-RepositoryName
    Value:
      Ref: EcrRepo


Resources:
  EcrRepo:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName:
        Fn::Sub: ${AWS::StackName}
...
